title: David Turner says...
author: ""
baseurl: "/"
url: "https://davecturner.github.io"
twitter_username: "DaveCTurner"
mastodon_username: "davecturner"
mastodon_instance: "mastodon.online"

markdown: kramdown
theme: minima
plugins:
  - jekyll-feed
