name:                uncrossing-diagrams
version:             0.1.0.0
github:              "githubuser/uncrossing-diagrams"
license:             BSD3
author:              "Author name here"
maintainer:          "example@example.com"
copyright:           "2018 Author name here"

description:         Please see the README on GitHub at <https://github.com/githubuser/uncrossing-diagrams#readme>

dependencies:
- base >= 4.7 && < 5
- cairo

executables:
  uncrossing-diagrams:
    main:                Main.hs
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
