name:                timezone-diagrams
version:             0.1.0.0
license:             BSD3
author:              "Author name here"
maintainer:          "example@example.com"
copyright:           "2018 Author name here"

dependencies:
- base >= 4.7 && < 5
- cairo
- pango
- mtl

executables:
  timezone-diagrams:
    main:                Main.hs
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
